name: neotoma-workshop
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-sf
  - r-geojsonsf
  - r-analogue
  - r-rioja
  - r-vegan
  - r-remotes
  - r-pacman
  - r-leaflet
  - r-dt
  - r-raster
  - r-terra
  - r-devtools
  - r-knitr
  - r-magrittr
  - r-MASS
  - r-class
  - r-proxy
  - r-e1071
  - r-KernSmooth
  - r-classInt
  - r-DBI
  - r-Rcpp
  - r-wk
  - r-s2
  - r-units
  - r-sf
  - r-geojsonsf
  - r-cli
  - r-glue
  - r-lifecycle
  - r-vctrs
  - r-purrr
  - r-generics
  - r-timechange
  - r-lubridate
  - r-curl
  - r-jsonlite
  - r-mime
  - r-sys
  - r-askpass
  - r-openssl
  - r-R6
  - r-httr
  - r-utf8
  - r-pillar
  - r-fansi
  - r-pkgconfig
  - r-tibble
  - r-withr
  - r-tidyselect
  - r-dplyr
  - r-gtools
  - r-lazyeval
  - r-crosstalk
  - r-cachem
  - r-jquerylib
  - r-memoise
  - r-fs
  - r-rappdirs
  - r-sass
  - r-bslib
  - r-fontawesome
  - r-tinytex
  - r-rmarkdown
  - r-htmlwidgets
  - r-leaflet.providers
  - r-png
  - r-lattice
  - r-sp
  - r-terra
  - r-raster
  - r-RColorBrewer
  - r-farver
  - r-labeling
  - r-colorspace
  - r-munsell
  - r-viridisLite
  - r-scales
  - r-leaflet
  - r-assertthat
  - r-stringi
  - r-stringr
  - r-crayon
  - r-hms
  - r-prettyunits
  - r-progress
  - r-uuid
  - r-tidyr
  - r-webR

  - python>=3.11,<3.13
  - altair-all=5.5.*
  - vega_datasets=0.9.0
  - pandas=1.5.*
  - jupyter
  - quarto
  - pip
