name: neotoma-workshop
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-sf
  
  - python>=3.11,<3.13
  - altair-all=5.5.*
  - vega_datasets=0.9.0
  - pandas=1.5.*
  - jupyter
  - quarto
  - pip
