name: "Deploy a PR preview to the gh-pages branch"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - 'main'

concurrency: preview-${{ github.ref }}

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout the PR version of the website repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libglpk-dev \
            libcurl4-openssl-dev

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4' # Or the specific R version you want to use

      - name: Setup the environment
        if: github.event.action != 'closed' # Skip the build if the PR has been closed; just run the clean up steps
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          init-shell: bash
          cache-environment: true
          post-cleanup: none
      
      - name: Install R packages from GitHub
        run: |
          Rscript -e "remotes::install_github('NeotomaDB/neotoma2@webr')"
          Rscript -e "install.packages('curl')"

      - name: Install neotoma2 package
        run: |
          Rscript -e "install.packages('./neotoma2_1.0.6.tgz', repos = NULL, type = 'source')"

      - name: Build the PR version of the website
        if: github.event.action != 'closed' # Skip the build if the PR has been closed; just run the clean up steps
        run: quarto render
        shell: bash -el {0}  # Required to see the mamba init env

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site/